### PR TITLE
Nchar psid to 7

### LINKED ISSUE #5: remove zipcodes from get_metadata.R
Since we're not supporting zipcodes (at least for now), `get_metadata.R` and associated docs and tests should remove all references to `zipcode` argument. @ERGZ - can you take a look at this?

### PR DESCRIPTION
**Pull request by richpauloo**
Fixes #5 and #11 . 

Updates: 

* New pkg objects have column psid of class character with nchar(psid) == 7 via left-padded zeros.  
* S3 bucket has corresponding tables named by 7 character psids.  
* `get_metadata()` now only takes a county argument (instead of zipcode and county), and does approximate county name matching. 
* tests for `get_data` and `get_metadata` have been updated, and pass.  
* geting-started.Rmd vignette has been updated with new pkg objects. 
* pkgdown site has been rebuilt.

### CODE REVIEW

**Review by ergz — COMMENTED** [review]
looks good, once merged we need to remove the zipcode parameter for get_water_system, unless you want to make the change, commit and push this same pull request

**Review by ergz — APPROVED** [review]

**Comment by richpauloo** [comment]
> looks good, once merged we need to remove the zipcode parameter for get_water_system, unless you want to make the change, commit and push this same pull request

If you check out `get_metadata.R`, I already removed the zipcode argument. The function only takes a county argument, and does some fuzzy matching to provide the user alternate counties if the input county is invalid.

**Comment by ergz** [comment]
oops yeah sorry thought I left the comment on a line of code, I just meant remove the zip parameters roxygen get_water_system

**Comment by richpauloo** [comment]
I'm not sure what that means. If it's a quick fix, would you mind committing it?

**Pull request merged**
